// <auto-generated />
using System;
using ActivityStatusPing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivityStatusPing.Migrations
{
    [DbContext(typeof(ActivityStatusPingContext))]
    [Migration("20231120003703_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ActivityStatusPing.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastActive = new DateTime(2023, 11, 20, 0, 37, 3, 180, DateTimeKind.Utc).AddTicks(1619),
                            Username = "Josh"
                        },
                        new
                        {
                            Id = 2,
                            LastActive = new DateTime(2023, 11, 20, 0, 37, 3, 180, DateTimeKind.Utc).AddTicks(1620),
                            Username = "Michelle"
                        },
                        new
                        {
                            Id = 3,
                            LastActive = new DateTime(2023, 11, 20, 0, 37, 3, 180, DateTimeKind.Utc).AddTicks(1621),
                            Username = "Shane"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
